<?php

namespace App\Exports;

use App\Models\Company;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class CompanyExport implements FromCollection, WithHeadings
{
    /**
     * @return \Illuminate\Support\Collection
     */
    public function collection()
    {
        return Company::with(['createdBy', 'salesUser.branch', 'department'])->get((new Company)->getFillable())->map(function ($data, $key) {
            return [
                'sr_no' => ($key + 1),
                'company_name' => $data->company_name,
                'contact_person' => $data->contact_person,
                'crid' => $data->crid,
                'customer_code' => $data->customer_code,
                'position' => $data->position,
                'mobile_no' => $data->mobile_no,
                'email' => $data->email,
                'po_box' => $data->po_box,
                'street' => $data->street,
                'city' => $data->city,
                'vat' => $data->vat,
                'construction' => $data->construction ? 'Construction' : '',
                'food' => $data->food ? 'Food' : '',
                'rental' => $data->rental ? 'Rental' : '',
                'logistics' => $data->logistics ? 'Logistics' : '',
                'describe_other' => $data->describe_other,
                'national_address' => $data->national_address,
                'hino_pick_up' => $data->hino_pick_up,
                'hino_light_duty_truck' => $data->hino_light_duty_truck,
                'hino_medium_duty_truck' => $data->hino_medium_duty_truck,
                'hino_heavy_duty_truck' => $data->hino_heavy_duty_truck,
                'hino_total' => $data->hino_total,
                'hino_oldest' => $data->hino_oldest,
                'hino_latest' => $data->hino_latest,
                'isuzu_pick_up' => $data->isuzu_pick_up,
                'isuzu_light_duty_truck' => $data->isuzu_light_duty_truck,
                'isuzu_medium_duty_truck' => $data->isuzu_medium_duty_truck,
                'isuzu_heavy_duty_truck' => $data->isuzu_heavy_duty_truck,
                'isuzu_total' => $data->isuzu_total,
                'isuzu_oldest' => $data->isuzu_oldest,
                'isuzu_latest' => $data->isuzu_latest,
                'fuso_pick_up' => $data->fuso_pick_up,
                'fuso_light_duty_truck' => $data->fuso_light_duty_truck,
                'fuso_medium_duty_truck' => $data->fuso_medium_duty_truck,
                'fuso_heavy_duty_truck' => $data->fuso_heavy_duty_truck,
                'fuso_total' => $data->fuso_total,
                'fuso_oldest' => $data->fuso_oldest,
                'fuso_latest' => $data->fuso_latest,
                'sitrak_pick_up' => $data->sitrak_pick_up,
                'sitrak_light_duty_truck' => $data->sitrak_light_duty_truck,
                'sitrak_medium_duty_truck' => $data->sitrak_medium_duty_truck,
                'sitrak_heavy_duty_truck' => $data->sitrak_heavy_duty_truck,
                'sitrak_total' => $data->sitrak_total,
                'sitrak_oldest' => $data->sitrak_oldest,
                'sitrak_latest' => $data->sitrak_latest,
                'sany_pick_up' => $data->sany_pick_up,
                'sany_light_duty_truck' => $data->sany_light_duty_truck,
                'sany_medium_duty_truck' => $data->sany_medium_duty_truck,
                'sany_heavy_duty_truck' => $data->sany_heavy_duty_truck,
                'sany_total' => $data->sany_total,
                'sany_oldest' => $data->sany_oldest,
                'sany_latest' => $data->sany_latest,
                'shacman_pick_up' => $data->shacman_pick_up,
                'shacman_light_duty_truck' => $data->shacman_light_duty_truck,
                'shacman_medium_duty_truck' => $data->shacman_medium_duty_truck,
                'shacman_heavy_duty_truck' => $data->shacman_heavy_duty_truck,
                'shacman_total' => $data->shacman_total,
                'shacman_oldest' => $data->shacman_oldest,
                'shacman_latest' => $data->shacman_latest,
                'faw_pick_up' => $data->faw_pick_up,
                'faw_light_duty_truck' => $data->faw_light_duty_truck,
                'faw_medium_duty_truck' => $data->faw_medium_duty_truck,
                'faw_heavy_duty_truck' => $data->faw_heavy_duty_truck,
                'faw_total' => $data->faw_total,
                'faw_oldest' => $data->faw_oldest,
                'faw_latest' => $data->faw_latest,
                'sinotruk_pick_up' => $data->sinotruk_pick_up,
                'sinotruk_light_duty_truck' => $data->sinotruk_light_duty_truck,
                'sinotruk_medium_duty_truck' => $data->sinotruk_medium_duty_truck,
                'sinotruk_heavy_duty_truck' => $data->sinotruk_heavy_duty_truck,
                'sinotruk_total' => $data->sinotruk_total,
                'sinotruk_oldest' => $data->sinotruk_oldest,
                'sinotruk_latest' => $data->sinotruk_latest,
                'man_pick_up' => $data->man_pick_up,
                'man_light_duty_truck' => $data->man_light_duty_truck,
                'man_medium_duty_truck' => $data->man_medium_duty_truck,
                'man_heavy_duty_truck' => $data->man_heavy_duty_truck,
                'man_total' => $data->man_total,
                'man_oldest' => $data->man_oldest,
                'man_latest' => $data->man_latest,
                'volvo_pick_up' => $data->volvo_pick_up,
                'volvo_light_duty_truck' => $data->volvo_light_duty_truck,
                'volvo_medium_duty_truck' => $data->volvo_medium_duty_truck,
                'volvo_heavy_duty_truck' => $data->volvo_heavy_duty_truck,
                'volvo_total' => $data->volvo_total,
                'volvo_oldest' => $data->volvo_oldest,
                'volvo_latest' => $data->volvo_latest,
                'mercedes_pick_up' => $data->mercedes_pick_up,
                'mercedes_light_duty_truck' => $data->mercedes_light_duty_truck,
                'mercedes_medium_duty_truck' => $data->mercedes_medium_duty_truck,
                'mercedes_heavy_duty_truck' => $data->mercedes_heavy_duty_truck,
                'mercedes_total' => $data->mercedes_total,
                'mercedes_oldest' => $data->mercedes_oldest,
                'mercedes_latest' => $data->mercedes_latest,
                'ud_pick_up' => $data->ud_pick_up,
                'ud_light_duty_truck' => $data->ud_light_duty_truck,
                'ud_medium_duty_truck' => $data->ud_medium_duty_truck,
                'ud_heavy_duty_truck' => $data->ud_heavy_duty_truck,
                'ud_total' => $data->ud_total,
                'ud_oldest' => $data->ud_oldest,
                'ud_latest' => $data->ud_latest,
                'other_pick_up' => $data->other_pick_up,
                'other_light_duty_truck' => $data->other_light_duty_truck,
                'other_medium_duty_truck' => $data->other_medium_duty_truck,
                'other_heavy_duty_truck' => $data->other_heavy_duty_truck,
                'other_total' => $data->other_total,
                'other_oldest' => $data->other_oldest,
                'other_latest' => $data->other_latest,
                'jeddah' => $data->jeddah ? 'Jeddah' : '',
                'madina' => $data->madina ? 'Madina' : '',
                'riyadh' => $data->riyadh ? 'Riyadh' : '',
                'dammam' => $data->dammam ? 'Dammam' : '',
                'al_khobar' => $data->al_khobar ? 'AL-Khobar' : '',
                'abha' => $data->abha ? 'Abha' : '',
                'hafr_batin' => $data->hafr_batin ? 'Hafr Batin' : '',
                'makkah' => $data->makkah ? 'Makkah' : '',
                'alyth' => $data->alyth ? 'Alyth' : '',
                'yanbu' => $data->yanbu ? 'Yanbu' : '',
                'buraidah' => $data->buraidah ? 'Buraidah' : '',
                'hail' => $data->hail ? 'Hail' : '',
                'al_baha' => $data->al_baha ? 'Al-Baha' : '',
                'alqassim' => $data->alqassim ? 'Alqassim' : '',
                'najran' => $data->najran ? 'Najran' : '',
                'jizan' => $data->jizan ? 'Jizan' : '',
                'khamis' => $data->khamis ? 'Khamis' : '',
                'tabuk' => $data->tabuk ? 'Tabuk' : '',
                'taif' => $data->taif ? 'Taif' : '',
                'neom' => $data->neom ? 'Neom' : '',
                'jubail' => $data->jubail ? 'Jubail' : '',
                'other_cities' => $data->other_cities,
                'new_vehicle_inquiry' => $data->new_vehicle_inquiry,
                'vehicle_shelf_life' => $data->vehicle_shelf_life,
                'coordinates' => $data->coordinates,
                'custownws_no_of_ws' => $data->custownws_no_of_ws,
                'custownws_no_of_tech' => $data->custownws_no_of_tech,
                'custownws_tech_languages' => $data->custownws_tech_languages,
                'custownws_oil_used' => $data->custownws_oil_used,
                'custownws_parts_genuine' => $data->custownws_parts_genuine ? 'Genuine' : '',
                'custownws_parts_non_genunine' => $data->custownws_parts_non_genunine ? 'Non-Genuine' : '',
                'custownws_parts_mix' => $data->custownws_parts_mix ? 'Mix' : '',
                'custownws_parts_source' => $data->custownws_parts_source,
                'locws_noof_ws' => $data->locws_noof_ws,
                'locws_name_of_ws' => $data->locws_name_of_ws,
                'locws_noof_tech' => $data->locws_noof_tech,
                'locws_approx_price' => $data->locws_approx_price,
                'locws_parts_utilized' => $data->locws_parts_utilized,
                'hinod_city' => $data->hinod_city,
                'hinod_amc_lvl' => $data->hinod_amc_lvl,
                'l12m_parts_1half' => $data->l12m_parts_1half,
                'l12m_parts_2half' => $data->l12m_parts_2half,
                'l12m_parts_date' => $data->l12m_parts_date,
                'l12m_service_1half' => $data->l12m_service_1half,
                'l12m_service_2half' => $data->l12m_service_2half,
                'l12m_service_date' => $data->l12m_service_date,
                'l12m_sales_1half' => $data->l12m_sales_1half,
                'l12m_sales_2half' => $data->l12m_sales_2half,
                'l12m_sales_date' => $data->l12m_sales_date,
                'customer_voice' => $data->customer_voice,
                'aftersales_contact_person' => $data->aftersales_contact_person,
                'title' => $data->title,
                'mobile' => $data->mobile,
                'visit_date' => $data->visit_date,
                'visit_time' => $data->visit_time,
                'department' => optional($data->department)->name,
                'customer_satisfaction' => $data->customer_satisfaction,
                'sales_user_id' => $data->sales_user_id === 0 ? 'All' : $data->sales_user_id,
                'sales_user_name' => $data->salesUser->name ?? 'All',
                'sales_user_branch' => $data->salesUser->branch->name ?? 'All',
            ];
        });
    }

    public function headings(): array
    {
        return [
            'Sr. No',
            'Company name',
            'Contact person',
            'CR/ID',
            'Customer Code',
            'Position',
            'Mobile No.',
            'Email',
            'P.O. Box',
            'Street',
            'City',
            'VAT',
            'Construction',
            'Food',
            'Rental',
            'Logistics',
            'Describe Other',
            'National Address',
            'Hino - Pick-up',
            'Hino - Light Duty Truck',
            'Hino - Medium Duty Truck',
            'Hino - Heavy Duty Truck',
            'Hino - Total',
            'Hino - Oldest',
            'Hino - Latest',
            'ISUZU - Pick-up',
            'ISUZU - Light Duty Truck',
            'ISUZU - Medium Duty Truck',
            'ISUZU - Heavy Duty Truck',
            'ISUZU - Total',
            'ISUZU - Oldest',
            'ISUZU - Latest',
            'FUSO - Pick-up',
            'FUSO - Light Duty Truck',
            'FUSO - Medium Duty Truck',
            'FUSO - Heavy Duty Truck',
            'FUSO - Total',
            'FUSO - Oldest',
            'FUSO - Latest',
            'Sitrak Pick Up',
            'Sitrak Light Duty Truck',
            'Sitrak Medium Duty Truck',
            'Sitrak Heavy Duty Truck',
            'Sitrak Total',
            'Sitrak Oldest',
            'Sitrak Latest',
            'Sany Pick Up',
            'Sany Light Duty Truck',
            'Sany Medium Duty Truck',
            'Sany Heavy Duty Truck',
            'Sany Total',
            'Sany Oldest',
            'Sany Latest',
            'Shacman Pick Up',
            'Shacman Light Duty Truck',
            'Shacman Medium Duty Truck',
            'Shacman Heavy Duty Truck',
            'Shacman Total',
            'Shacman Oldest',
            'Shacman Latest',
            'Faw Pick Up',
            'Faw Light Duty Truck',
            'Faw Medium Duty Truck',
            'Faw Heavy Duty Truck',
            'Faw Total',
            'Faw Oldest',
            'Faw Latest',
            'Sinotruk Pick Up',
            'Sinotruk Light Duty Truck',
            'Sinotruk Medium Duty Truck',
            'Sinotruk Heavy Duty Truck',
            'Sinotruk Total',
            'Sinotruk Oldest',
            'Sinotruk Latest',
            'Man Pick Up',
            'Man Light Duty Truck',
            'Man Medium Duty Truck',
            'Man Heavy Duty Truck',
            'Man Total',
            'Man Oldest',
            'Man Latest',
            'Volvo Pick Up',
            'Volvo Light Duty Truck',
            'Volvo Medium Duty Truck',
            'Volvo Heavy Duty Truck',
            'Volvo Total',
            'Volvo Oldest',
            'Volvo Latest',
            'Mercedes Pick Up',
            'Mercedes Light Duty Truck',
            'Mercedes Medium Duty Truck',
            'Mercedes Heavy Duty Truck',
            'Mercedes Total',
            'Mercedes Oldest',
            'Mercedes Latest',
            'Ud Pick Up',
            'Ud Light Duty Truck',
            'Ud Medium Duty Truck',
            'Ud Heavy Duty Truck',
            'Ud Total',
            'Ud Oldest',
            'Ud Latest',
            'Other Pick Up',
            'Other Light Duty Truck',
            'Other Medium Duty Truck',
            'Other Heavy Duty Truck',
            'Other Total',
            'Other Oldest',
            'Other Latest',
            'Jeddah',
            'Madina',
            'Riyadh',
            'Dammam',
            'AL-Khobar',
            'Abha',
            'Hafr Batin',
            'Makkah',
            'Alyth',
            'Yanbu',
            'Buraidah',
            'Hail',
            'Al-Baha',
            'Alqassim',
            'Najran',
            'Jizan',
            'Khamis',
            'Tabuk',
            'Taif',
            'Neom',
            'Jubail',
            'Other Cities',
            'New vehicle Inquiry',
            'Vehicle Shelf Life',
            'Coordinates',
            'CustOwnWS No. of WS',
            'CustOwnWS No. of Tech',
            'CustOwnWS Tech Languages',
            'CustOwnWS Oil Used',
            'CustOwnWS Parts Genuine',
            'CustOwnWS Parts Non-Genunine',
            'CustOwnWS Parts Mix',
            'CustOwnWS Parts Source',
            'LocWS No.of WS',
            'LocWS Name.of WS',
            'LocWS No.of Tech',
            'LocWS Approx. Price',
            'LocWS Parts Utilized',
            'HinoD City',
            'HinoD AMC Lvl.',
            'L12M Parts 1half',
            'L12M Parts 2half',
            'L12M Parts Date',
            'L12M Service 1half',
            'L12M Service 2half',
            'L12M Service Date',
            'L12M Sales 1half',
            'L12M Sales 2half',
            'L12M Sales Date',
            'Cutomer Voice',
            'Aftersales Contact Person',
            'Title',
            'Mobile',
            'visit Date',
            'visit Time',
            'Dept',
            'Customer Satisfation',
            'Sales User Id',
            'Sales User Name',
            'Sales User Branch',
        ];
    }
}
